### PR TITLE
[bitnami/wordpress-nginx] Reverting change that broke behavior

### LINKED ISSUE #12995: [bitnami/wordpress-nginx] Wordpress startup is broken in latest wordpress-nginx
### Name and Version

bitnami/wordpress-nginx v6.0.3

### What steps will reproduce the bug?

The startup of 6.0.3 gives us an error with sed that does _not_ present with 6.0.2.

```
wordpress 18:51:29.39 Welcome to the Bitnami wordpress-nginx container
wordpress 18:51:29.39 Subscribe to project updates by watching https://github.com/bitnami/containers
wordpress 18:51:29.39 Submit issues and feature requests at https://github.com/bitnami/containers/issues
wordpress 18:51:29.40
wordpress 18:51:29.40 INFO  ==> ** Starting WordPress setup **
wordpress 18:51:29.42 INFO  ==> Validating settings in NGINX_* env vars
wordpress 18:51:29.45 INFO  ==> No custom scripts in /docker-entrypoint-initdb.d
wordpress 18:51:29.47 INFO  ==> Initializing NGINX
realpath: /bitnami/nginx/conf/vhosts: No such file or directory
sed: can't read /opt/bitnami/nginx/conf/server_blocks/default-https-server-block.conf: No such file or directory
```

I don't see exactly where this is happening, but it's surely not happening with our build process when we source your image. I can post a sanitized version of our `Dockerfile` if necessary.

### What is the expected behavior?

The image has no failures on startup

### What do you see instead?

We get an error and it bails early

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by bengaywins**
### Description of the change

This PR reverts behavior that broke the image for us and likely others.

### Benefits

The behavior is no longer broken.

### Possible drawbacks

No idea, but I would argue behavior changes should not be in minor versions.

### Applicable issues

  - fixes #12995

### CODE REVIEW

**Comment by carrodher** [comment]
Thanks for creating this PR. Please, note it is needed to sign the commits. Your signature certifies that you wrote the patch or otherwise have the right to contribute the material. You can find more info about this topic, in [the “Sign your work” section from the contributing guidelines](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#sign-your-work).

In the same way, could you please provide more info about what is broken?

**Comment by bengaywins** [comment]
@carrodher I have signed my commit and I see it shows as verified now.

**Comment by carrodher** [comment]
It seems commits are still unsigned and the action is failing, could you please follow the steps described in the [failing action](https://github.com/bitnami/containers/pull/22437/checks?check_run_id=11040953268)?

**Comment by bengaywins** [comment]
Closing this PR to open a new one with a clean fork. Sorry.

**Pull request closed without merging**
