### PR TITLE
[bitnami/pgbouncer] Specify userlist.txt file content by env var

### PR DESCRIPTION
**Pull request by sondn98**
See [Issue-30080](https://github.com/bitnami/containers/issues/30080)

### CODE REVIEW

**Comment by sondn98** [comment]
@javsalgar @carrodher @fmulero Any update on this?

**Review by fmulero — CHANGES_REQUESTED** [review]
Thanks a lot @sondn98 for this contribution. It looks great!

I have only a little suggestion, Could you document this new variable in the README file?

**Review by fmulero — APPROVED** [review]
LGTM. Thanks @sondn98

**Comment by iacob28** [comment]
Hi @fmulero 

Is there any way I can specify multiple users? The echo as is written now it doesn't parse the new line character.
I've tried something like this inside the docker-compose file

 `- PGBOUNCER_USERLIST="user1" "pass1"$'\n'"user2" "pass2"`

**Comment by iacob28** [comment]
For now, I just use an init script to append the users to the `userlist.txt`. I've used this method because even If I've bind mounted my `/conf` directory from the container, the container rewrites my `userlist.txt` file every time I've restarted the container.

This is the script

`PGBOUNCER_USERLIST=(
  "\"user1\" \"pass1\""
  "\"user2\" \"pass2\""
)

for user in "${PGBOUNCER_USERLIST[@]}"; do
  echo "$user" >> "$PGBOUNCER_AUTH_FILE"
done
`

**Pull request merged**
