### PR TITLE
[bitnami/grafana] Ensure bitnami/grafana folder is created with usable permissions

### LINKED ISSUE #52238: [bitnami/grafana] Running grafana image with user init script causes error
### Name and Version

grafana:10.2.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Create a shell script
2. Run the image, mounting the shell script to the `/docker-entrypoint-init.d/` directory

For example:
```
$ docker run --rm -v $(pwd)/foo.sh:/docker-entrypoint-init.d/foo.sh -ti docker.io/bitnami/grafana:10.2.0-debian-11-r0
```

### What is the expected behavior?

The script runs, and the container starts

### What do you see instead?

```
grafana 14:28:54.37 
grafana 14:28:54.37 Welcome to the Bitnami grafana container
grafana 14:28:54.37 Subscribe to project updates by watching https://github.com/bitnami/containers
grafana 14:28:54.38 Submit issues and feature requests at https://github.com/bitnami/containers/issues
grafana 14:28:54.38 
mkdir: cannot create directory '/bitnami': Permission denied
```

### Additional information

Presumably from here:  https://github.com/bitnami/containers/blob/8bb5534a6c4b6562ba3f6fa7191f6d96d214b83d/bitnami/grafana/10/debian-11/rootfs/post-init.sh#L16

### PR DESCRIPTION
**Pull request by bpfoster**
### Description of the change
Ensures that  `/bitnami/grafana` folder is created with usable permissions.  I believe this follows the examples of other bitnami images.

Without this folder being created, adding user init scripts leads to an error on startup:
`mkdir: cannot create directory '/bitnami': Permission denied`

### Benefits
Necessary folders are created with proper permissions so that the image can run as the non-root user.

### Possible drawbacks
None

### Applicable issues
- fixes #52238

### CODE REVIEW

**Comment by bpfoster** [comment]
Un-stale

**Comment by CeliaGMqrz** [comment]
Hi @bpfoster,

Sorry for my late response. Thanks for your contribution!

Maybe we could maintain consistency by using `grafana_env_var_value` as well?

**Comment by bpfoster** [comment]
Hi @CeliaGMqrz no problem for the delay!

If we use the `grafana_env_var_value` function, it would [require the variable being prefixed](https://github.com/bitnami/containers/blob/main/bitnami/grafana/10/debian-11/rootfs/opt/bitnami/scripts/libgrafana.sh#L35-L36) with `GF_` (or `GRAFANA_CFG_`).
This would move it from the "Grafana paths" to the "Grafana configurations" section [in the env file](https://github.com/bitnami/containers/blob/main/bitnami/grafana/10/debian-11/rootfs/opt/bitnami/scripts/grafana-env.sh#L57-L89).

Happy to make that change if you'd prefer it that way, just want to confirm the change to the env variable as well as I'm not familiar with the separate naming conventions.

**Comment by bpfoster** [comment]
Un-stale

**Comment by CeliaGMqrz** [comment]
Hi @bpfoster,

Thanks for your patience and taking care of this issue.

In effect, this change would require to set the `GF_ ` prefix and move it to the Grafana configuration section in the [env file](https://github.com/bitnami/containers/blob/main/bitnami/grafana/10/debian-11/rootfs/opt/bitnami/scripts/grafana-env.sh#L69).

**Comment by bpfoster** [comment]
@CeliaGMqrz sounds good.  Variable is now named `GF_VOLUME_DIR` and is reference by the `grafana_env_var_value` function per your recommendation.

**Comment by bpfoster** [comment]
Un-stale

**Comment by CeliaGMqrz** [comment]
Hi @bpfoster, thanks for your feedback.

Sorry for the delay after the vacation.

The changes have not been applied correctly. Could you fix the DCO issue?

**Comment by bpfoster** [comment]
@CeliaGMqrz my apologies for missing the commit signing.  Amended the commit and DCO check is now passing.

**Comment by bpfoster** [comment]
Un-stale

**Review by CeliaGMqrz — APPROVED** [review]
Hi, @bpfoster 

Sorry to keep you waiting with this PR. 

I have consulted with the team and we are going to merge these changes for a temporary workaround. I will create an internal task to review the persistence logic of this container in accordance with grafana configuration to adapt this feature in a cleaner way.

Thanks for your contribution!

**Pull request merged**
