### PR TITLE
[bitnami/nginx] Specify ciphers suites and set strong ciphers

### PR DESCRIPTION
**Pull request by d4rklynk**
It's better to specify cipher suites to avoid having too many ciphers authorized.

It allows better control of which cipher suites you use.

Only strong ciphers have been chosen.

The cipher have been choosed based on https://english.ncsc.nl/publications/publications/2021/january/19/it-security-guidelines-for-transport-layer-security-2.1

Only a few very very old version of somes OSes will not work (like OX 10.10 that ended 6 years ago).
You can check a handshake simulation example [here](https://www.ssllabs.com/ssltest/analyze.html?d=grapheneos.org&s=192.99.43.50) with these ciphers.

### CODE REVIEW

**Comment by d4rklynk** [comment]
At the very least, we should set them up as so:
```nginx
ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384;
ssl_prefer_server_ciphers off;
```
I'm not sure for the prioritize chacha, I need to check again.

Based on:
- https://www.ssl.com/guide/tls-standards-compliance/
- https://ssl-config.mozilla.org/#server=nginx&version=1.17.7&config=intermediate&openssl=1.1.1k&guideline=5.7

**Comment by jotamartos** [comment]
Hi @d4rklynk,

Thank you for your contribution and sorry for the delay. Please let us review and test the changes before merging them. 

Thanks

**Comment by jotamartos** [comment]
Hi @d4rklynk,

I just reviewed your changes and proposed some changes according to the information you provided. Could you please review them and ping me here in this main thread so I get notified? 

Thanks

**Comment by d4rklynk** [comment]
Hi, I don't understand, I don't see any review.

**Comment by d4rklynk** [comment]
Hi, when you can, could you please complete your review? You didn't finish the review so I can't see it atm. I'm looking forward. Thanks!
image

**Review by jotamartos — CHANGES_REQUESTED** [review]

**Comment by jotamartos** [comment]
So sorry about the review submission 😅  I thought I clicked on it.

**Comment by d4rklynk** [comment]
LGTM, Just keep in mind that DNS is weak under somes circunstamces -> https://ciphersuite.info/cs/TLS_DHE_RSA_WITH_CHACHA20_POLY1305_SHA256/

Is it relevant to add strong ciphers commented out ?

**Comment by jotamartos** [comment]
>Is it relevant to add strong ciphers commented out ? (in case someones needs it)

I think that may confuse users. If the user knows what he's configuring, he'll set the list of ciphers he really wants to use but if he doesn't have enough experience with NGINX, he will probably end up enabling/disabling ciphers he does/doesn't really need. 

Let me migrate this information to our systems and will merge this PR after that. 

Thanks

**Review by jotamartos — APPROVED** [review]
Thank you for this contribution!

**Pull request merged**
