### PR TITLE
Fix mysqldump master database

### PR DESCRIPTION
**Pull request by michel-silva**
### Description of the change
This PR https://github.com/bitnami/containers/pull/54038 adds the functionality to dump master database when missing binary files. Its a solution to this issue https://github.com/bitnami/containers/issues/54028.

But, was checked that when the number of slaves was increased, the replication broken. 

This new PR fixes this issue, that occurs when increasing the number of slaves.

### CODE REVIEW

**Comment by mostafa-rz** [comment]
@michel-silva Many thanks for the fix. I can confirm all the issues mentioned [here](https://github.com/bitnami/containers/pull/54038#issuecomment-1893922128), are solved.

**Comment by aoterolorenzo** [comment]
Hi @michel-silva,

So sorry for the mess, I completely missed this case. Could you resolve the comflicts? Let's merge this!

**Comment by michel-silva** [comment]
Hi @aoterolorenzo,

Don't worry. I will resolve the conflicts today and let you know. 

Thank for your reply.

**Comment by michel-silva** [comment]
@aoterolorenzo The conflicts are solved. Could you check please?

**Comment by michel-silva** [comment]
@aoterolorenzo I updated the PR.. Could you check?

**Comment by aoterolorenzo** [comment]
Hi @michel-silva,

Sorry for the delay again: We have been performing several breaking changes for the containers, making debian-12 the default distro for all our containers in automated batches so I just preferred to wait to merge this one, since our internal pipelines auto-generate all the scripts (so acutally I have to reproduce and propose this fix in our internal system, to avoid the pipelines tread down this changes). Please, let me see if I myself can solve the conflicts, and set up the internal code proposal. I will be back to you later

**Comment by aoterolorenzo** [comment]
The fix is failing due to a linter problem in our internal systems:

`libmysql.sh:197:43: warning: Quote this to prevent word splitting. [SC2046]`

I'll try to fix it in your branch directly. Will be back later.

**Review by aoterolorenzo — APPROVED** [review]

**Pull request merged**
