### PR TITLE
[bitnami/joomla] Deprecate container

### PR DESCRIPTION
**Pull request by fmulero**
### Description of the change

Deprecate Joomla container

### CODE REVIEW

**Review by juan131 — APPROVED** [review]

**Comment by rstml** [comment]
No more Joomla?

**Comment by carrodher** [comment]
> No more Joomla?

I understand your concern regarding this deprecation. Joomla has been deprecated from the Bitnami catalog because our focus has shifted towards infrastructure solutions. As a result, we are phasing out certain web application assets to better align with our strategic direction.

**Comment by rstml** [comment]
Is there more info about this, maybe a blog post? What other apps/containers are planned to be deprecated?

**Comment by carrodher** [comment]
This is not a one-time action but an ongoing effort to ensure our catalog includes the most demanded applications. You can check all deprecated applications by looking for the [`-archived` suffix in DockerHub](https://hub.docker.com/?namespace=bitnami&search=archived).

**Pull request merged**
