### PR TITLE
[bitnami/postgresql] Created seperate config directory to allow for readonlyrootfilesystem

### LINKED ISSUE #52472: [bitnami/postgresql] Supporting read only filesystems
### Name and Version

bitnami/postgresql:16.0.0-debian-11-r15

### What is the problem this feature will solve?

The current bitnami images must run without immutable root filesystems which is quickly becoming a non-starter in some containerized environments. 
You can find many hardening guides suggesting the readOnlyRootFilesystem is enabled (NSA for example). 

### What is the feature you are proposing to solve the problem?

Moving the config directory at runtime from a template config directory to an active one would allow this.  
https://github.com/bitnami/containers/compare/main...JKrehling:containers:postgresql-read-only

### What alternatives have you considered?

Depending on the environment you can get around this. 

https://github.com/bitnami/charts/issues/5986

Considered workarounds like this to remount and move things on startup if deploying in kubernetes but was thinking there must be a better way than multiple containers and moving volumes around.

### PR DESCRIPTION
**Pull request by JKrehling**
### Description of the change

Moves the config files into the conf directory on startup to allow for readOnlyRootFilesystem 

### Benefits

Conf directory can be mounted separately without rewriting all the other bootstrap scripts 

### Possible drawbacks

Anyone mounting files directly into the conf directory would have them overwritten, they would have to mount them into temp-conf. 

### Applicable issues

- fixes #52472

### Additional information

docker build -t postgresql:rootest .

docker run -it --read-only --tmpfs=/tmp --tmpfs=/opt/bitnami/postgresql/conf --tmpfs=/opt/bitnami/postgresql/tmp -e ALLOW_EMPTY_PASSWORD=yes postgresql:rootest

### CODE REVIEW

**Comment by javsalgar** [comment]
Hi!

Thank you so much for the PR! Could you fix the DCO issue?

**Comment by JKrehling** [comment]
> Hi!
> 
> Thank you so much for the PR! Could you fix the DCO issue?

Should be good now. Thanks!

**Comment by JKrehling** [comment]
I did change the cp flag to use -u which should only update the files in the working conf directory if people are mounting things in there as well.  So it should just add the files if conf is empty.

**Comment by JKrehling** [comment]
@CeliaGMqrz 
Hi Celia, 
Was there something more needed from my end here for this review. 

Thanks!

**Comment by CeliaGMqrz** [comment]
Hi @JKrehling,

Thanks for your contribution. Our team is currently evaluating the best approach to address this issue. We appreciate your patience and support as we work towards a resolution.

**Comment by CeliaGMqrz** [comment]
Hi @JKrehling 

Thanks for your efforts in addressing this issue. Sorry for not notifying you sooner. 

As I mentioned, our team was already working on implementing this feature to ensure consistency with other assets. This feature is now available in the latest version, so we will be closing the PR. 

If you encounter any problems or difficulties, please feel free to open an issue. We appreciate your feedback.

**Pull request closed without merging**
