### PR TITLE
[bitnami/zookeeper] JVM memory customization fix

### LINKED ISSUE #18980: [bitnami/zookeeper] Unclear JVM memory customization management
### Name and Version

bitnami/zookeeper 12.1.2

### What architecture are you using?

None

### What steps will reproduce the bug?

Hello,

When providing heapSize parameter and a configuration file zoo.cfg using helm chart the memory parameter isn't considered. It takes the default value.

1- Environment: Kubernetes
2- Deploy the zookeeper helm chart with values:

>  `.Values.heapSize: 4567`
>  `.Values.existingConfigmap: myConfigMap`

3- Wait for deployment.
4- Enter zookeeper shell pod and check JVM parameters:
`ps -aux | more`
5- The Xmx value parameter will be set by default at 1000MB instead of the 4567MB requested in the values. 

### What is the expected behavior?

The expected behavior is to have the requested memory set for the JVM in heapSize parameter (here Xmx=4567m).
The fact of providing a zoo.cfg file through the confimap prevents this parameter from being used.

see:
https://github.com/bitnami/containers/blob/fe763b3a1290f819750f072a02b4444c67c8448d/bitnami/zookeeper/3.8/debian-11/rootfs/opt/bitnami/scripts/libzookeeper.sh#L150C46-L150C46

### What do you see instead?

```
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
1001           1 36.8  0.5 13605676 2957540 ?    Ssl  07:52 111:10 java -Dzookeeper.log.dir=/opt/bitnami/zookeeper/logs -Dzookeeper.log.file=zookeeper--server-clickhouse-zk-0.log -Dzookeeper.root.logger=INFO,CONSOLE -XX:+Heap
DumpOnOutOfMemoryError -XX:OnOutOfMemoryError=kill -9 %p -cp /opt/bitnami/zookeeper/bin/../zookeeper-server/target/classes:/opt/bitnami/zookeeper/bin/../build/classes:/opt/bitnami/zookeeper/bin/../zookeeper-server/target/lib/
*.jar:/opt/bitnami/zookeeper/bin/../build/lib/*.jar:/opt/bitnami/zookeeper/bin/../lib/zookeeper-prometheus-metrics-3.7.0.jar:/opt/bitnami/zookeeper/bin/../lib/zookeeper-jute-3.7.0.jar:/opt/bitnami/zookeeper/bin/../lib/zookeep
er-3.7.0.jar:/opt/bitnami/zookeeper/bin/../lib/snappy-java-1.1.7.7.jar:/opt/bitnami/zookeeper/bin/../lib/slf4j-log4j12-1.7.30.jar:/opt/bitnami/zookeeper/bin/../lib/slf4j-api-1.7.30.jar:/opt/bitnami/zookeeper/bin/../lib/simple
client_servlet-0.9.0.jar:/opt/bitnami/zookeeper/bin/../lib/simpleclient_hotspot-0.9.0.jar:/opt/bitnami/zookeeper/bin/../lib/simpleclient_common-0.9.0.jar:/opt/bitnami/zookeeper/bin/../lib/simpleclient-0.9.0.jar:/opt/bitnami/z
ookeeper/bin/../lib/netty-transport-native-unix-common-4.1.59.Final.jar:/opt/bitnami/zookeeper/bin/../lib/netty-transport-native-epoll-4.1.59.Final.jar:/opt/bitnami/zookeeper/bin/../lib/netty-transport-4.1.59.Final.jar:/opt/b
itnami/zookeeper/bin/../lib/netty-resolver-4.1.59.Final.jar:/opt/bitnami/zookeeper/bin/../lib/netty-handler-4.1.59.Final.jar:/opt/bitnami/zookeeper/bin/../lib/netty-common-4.1.59.Final.jar:/opt/bitnami/zookeeper/bin/../lib/ne
tty-codec-4.1.59.Final.jar:/opt/bitnami/zookeeper/bin/../lib/netty-buffer-4.1.59.Final.jar:/opt/bitnami/zookeeper/bin/../lib/metrics-core-4.1.12.1.jar:/opt/bitnami/zookeeper/bin/../lib/log4j-1.2.17.jar:/opt/bitnami/zookeeper/
bin/../lib/jline-2.14.6.jar:/opt/bitnami/zookeeper/bin/../lib/jetty-util-ajax-9.4.38.v20210224.jar:/opt/bitnami/zookeeper/bin/../lib/jetty-util-9.4.38.v20210224.jar:/opt/bitnami/zookeeper/bin/../lib/jetty-servlet-9.4.38.v2021
0224.jar:/opt/bitnami/zookeeper/bin/../lib/jetty-server-9.4.38.v20210224.jar:/opt/bitnami/zookeeper/bin/../lib/jetty-security-9.4.38.v20210224.jar:/opt/bitnami/zookeeper/bin/../lib/jetty-io-9.4.38.v20210224.jar:/opt/bitnami/z
ookeeper/bin/../lib/jetty-http-9.4.38.v20210224.jar:/opt/bitnami/zookeeper/bin/../lib/javax.servlet-api-3.1.0.jar:/opt/bitnami/zookeeper/bin/../lib/jackson-databind-2.10.5.1.jar:/opt/bitnami/zookeeper/bin/../lib/jackson-core-
2.10.5.jar:/opt/bitnami/zookeeper/bin/../lib/jackson-annotations-2.10.5.jar:/opt/bitnami/zookeeper/bin/../lib/commons-cli-1.4.jar:/opt/bitnami/zookeeper/bin/../lib/audience-annotations-0.12.0.jar:/opt/bitnami/zookeeper/bin/..
/zookeeper-*.jar:/opt/bitnami/zookeeper/bin/../zookeeper-server/src/main/resources/lib/*.jar:/opt/bitnami/zookeeper/bin/../conf: -Xmx1000m -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.local.only=false org.apa
che.zookeeper.server.quorum.QuorumPeerMain /opt/bitnami/zookeeper/bin/../conf/zoo.cfg
```

### Additional information

In order to only set the server memory we used `.Values.extraEnvVars` parameter to only set the memory for the `ZK_SERVER_HEAP` affecting the server and not the client.
Maybe separate parameters always be considered for:
- `ZK_SERVER_HEAP`
- `ZK_CLIENT_HEAP`

Regards

### PR DESCRIPTION
**Pull request by clemrodriguez**
Hello,

This PR is related to an open issue in bitnami/charts: https://github.com/bitnami/charts/issues/18980.

In this PR I propose to inject content of `$.Values.heapSize` into the `ZK_SERVER_HEAP` directly. This variable is used by `zkEnv.sh` that will add it properly to the `SERVER_JVMFLAGS` used by apache zookeeper to launch the JVM.

### Benefits
Those changes fix the following issues:
- `heapSize` value from helm chart _values.yaml_ is now taken into account even if a config file is provided
- `heapSize` value from helm chart _values.yaml_ only affects the server's JVM runtime (zkCli is unchanged avoiding OOM kill)
- it only affects Xmx parameter of the JVM

What it doesn't change:
- if JVM flags containing `Xms` and `Xmx` are passed in the config file they will be added by zkEnv.sh `ZK_SERVER_HEAP` leading to `SERVER_JVMFLAGS="-Xmx${DEFAULT_VALUE}m  ${JVMFLAGS}m"` which turn out to be: `SERVER_JVMFLAGS="-Xmx1000m  -Xms2048m -Xms2048m"` for `$.Values.heapSize=2048`

### Applicable issues

- fixes https://github.com/bitnami/charts/issues/18980

### Additional information
Thanks for your review

### CODE REVIEW

**Comment by javsalgar** [comment]
Hi!

Thank you so much for the PR! Could you fix the DCO issue?

**Review by joancafom — COMMENTED** [review]
Hi @clemrodriguez 

Thanks for the PR and sorry for the delay. I don't really see much value in the proposed changes, let me explain this a little bit more:

- As you said, the `ZK_SERVER_HEAP` is directly used by `zkEnv.sh`. There is really no need to export it here, it will work right away if you declare it in your `docker-compose.yaml` set up:

```diff
# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

version: '2'

services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.9
    ports:
      - '2181:2181'
    volumes:
      - 'zookeeper_data:/bitnami/zookeeper'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
+     - ZK_SERVER_HEAP=2048

volumes:
  zookeeper_data:
    driver: local
```

```console
$ docker-compose up
$ docker exec -it zookeeper_zookeeper_1 bash
> printenv | grep ZK
ZK_SERVER_HEAP=2048

> ps aux | grep "\-Xm"
java -Dzookeeper.log.dir=/opt/bitnami/zookeeper/logs ... -Xmx2048m -Xmx1024m -Xms1024m -Dzookeeper.electionPortBindRetry=0
```

- I don't really know the reasoning behind the current implementation for `ZOO_HEAP_SIZE`, but IMHO it should just be an alias of `ZK_SERVER_HEAP`. This way, the correct definition in `zookeeper-env.sh` could be something similar to:

```console
export ZK_SERVER_HEAP="${ZK_SERVER_HEAP:-"${ZOO_HEAP_SIZE:-1024}"}"
```

No additional config or logic would be required, and the approach is just simpler IMHO. WDYT?

**Comment by clemrodriguez** [comment]
Hello @joancafom ,

Thanks for your reply.

Indeed the definition in `zookeeper-env.sh` is providing the expected result and is simpler:
`export ZK_SERVER_HEAP="${ZK_SERVER_HEAP:-"${ZOO_HEAP_SIZE:-1024}"}"`

Best regards

**Comment by carrodher** [comment]
Thank you for initiating this pull request. We appreciate your effort. Just a friendly reminder that it's important to sign your commits. Adding your signature certifies that you either authored the patch or have the necessary rights to contribute the changes. You can find detailed information on how to do this in the [“Sign your work” section of our contributing guidelines](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#sign-your-work).

Feel free to reach out if you have any questions or need assistance with the signing process.

**Comment by clemrodriguez** [comment]
Hi @carrodher ,

Indeed I have issue to sign my commit, even after signed from what I believe, the DCO is failing and can't figure why.
Any help would be much appreciated.

Regards.

**Comment by carrodher** [comment]
[Here](https://github.com/bitnami/containers/pull/51502/checks?check_run_id=18997718505) you can see what is failing and what are possible remediations.

**Pull request closed without merging**
