### PR TITLE
[bitnami/dokuwiki] fix DOKU_INC path

### PR DESCRIPTION
**Pull request by kossmac**
### Description of the change

Sets auto_prepend_file in php.ini to let DokuWiki's templates and plugins know where DokuWiki really lives(default: "/opt/bitnami/dokuwiki") Since this container splits application from state files(/opt/bitnami/dokuwiki vs. /bitnami/dokuwiki) it is important that the DOKU_INC path is set accordingly. The PHP interpreter will prepend the file content specified in auto_prepend_file to every php file that gets executed.

### Benefits

Templates and plugins relying on the DOKU_INC path will work now(e.g. farmer plugin).

### Possible drawbacks

nothing known

### Additional information

As discussed with DokuWiki founder @splitbrain this is the best solution to get all templates and plugins to work.

### CODE REVIEW

**Comment by dgomezleon** [comment]
Hi @kossmac and @splitbrain.

Thanks for contributing. I have a question about this approach:

Could it be possible to add this logic to `doku.php`? Note this can be problematic since `/tmp` is cleaned up after every restart.

**Review by dgomezleon — CHANGES_REQUESTED** [review]
Great contribution.  Regarding [this](https://github.com/bitnami/containers/pull/12535#issuecomment-1309995942), I would use `dokuwiki/conf` instead, since it is persisted.

**Comment by kossmac** [comment]
@dgomezleon you're right, i moved the file to dokuwiki/conf now.

**Review by dgomezleon — APPROVED** [review]
LGTM

**Pull request merged**
