### PR TITLE
[bitnami/magento] Deprecate container

### PR DESCRIPTION
**Pull request by gongomgra**
### Description of the change

This PR removes Magento from the containers catalog.

### CODE REVIEW

**Review by andresbono — APPROVED** [review]

**Review by juan131 — APPROVED** [review]
LGTM

**Comment by a970032** [comment]
@gongomgra @juan131 ,
Why removing the folder? Is it not maintain anymore?

**Comment by juan131** [comment]
Hi @a970032 

Yes, Magento has been deprecated from the Bitnami Catalog.

**Comment by psy0rz** [comment]
does someone know what we should use now to deploy the OSS version of magento in docker?

**Comment by gongomgra** [comment]
@psy0rz thanks for your interest in using Bitnami. As Juan mentioned above, the Magento container has been removed from our catalog. Previously released images are still [available in DockerHub](https://hub.docker.com/r/bitnami/magento). 

You can find other ways of deploying the most recent version of the Magento application at https://bitnami.com/stack/magento

**Comment by driv** [comment]
It's not available in DockerHub anymore.

**Pull request merged**
