### PR TITLE
[bitnami/mlflow] support google-cloud-storage

### LINKED ISSUE #65108: [bitnami/mlflow] MLFlow missing package: google-cloud-storage
### Name and Version

bitnami/mlflow

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Right now we have MLFlow setup with GCP and relying on the bitnami image. Whenever we try log ML models to the tracking server it tries saving it under the hood to google cloud storage but fails due to missing package `google-cloud-storage` and its dependencies (google.auth included). To reproduce simply without having to setup the whole GCP server;

1. Load mlflow bitnami image.
2. Start python
2. Interpret `from google.auth.exceptions import DefaultCredentialsError` (as per https://github.com/mlflow/mlflow/blob/master/mlflow/store/artifact/gcs_artifact_repo.py)

### What is the expected behavior?

It imports correctly.

### What do you see instead?

```
Traceback (most recent call last):
  File "/opt/bitnami/python/lib/python3.10/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/bitnami/python/lib/python3.10/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/bitnami/python/lib/python3.10/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/bitnami/python/lib/python3.10/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/opt/bitnami/python/lib/python3.10/site-packages/mlflow/server/handlers.py", line 497, in wrapper
    return func(*args, **kwargs)
  File "/opt/bitnami/python/lib/python3.10/site-packages/mlflow/server/handlers.py", line 538, in wrapper
    return func(*args, **kwargs)
  File "/opt/bitnami/python/lib/python3.10/site-packages/mlflow/server/handlers.py", line 951, in _list_artifacts
    artifact_entities = _list_artifacts_for_proxied_run_artifact_root(
  File "/opt/bitnami/python/lib/python3.10/site-packages/mlflow/server/handlers.py", line 497, in wrapper
    return func(*args, **kwargs)
  File "/opt/bitnami/python/lib/python3.10/site-packages/mlflow/server/handlers.py", line 981, in _list_artifacts_for_proxied_run_artifact_root
    artifact_destination_repo = _get_artifact_repo_mlflow_artifacts()
  File "/opt/bitnami/python/lib/python3.10/site-packages/mlflow/server/handlers.py", line 175, in _get_artifact_repo_mlflow_artifacts
    _artifact_repo = get_artifact_repository(os.environ[ARTIFACTS_DESTINATION_ENV_VAR])
  File "/opt/bitnami/python/lib/python3.10/site-packages/mlflow/store/artifact/artifact_repository_registry.py", line 117, in get_artifact_repository
    return _artifact_repository_registry.get_artifact_repository(artifact_uri)
  File "/opt/bitnami/python/lib/python3.10/site-packages/mlflow/store/artifact/artifact_repository_registry.py", line 74, in get_artifact_repository
    return repository(artifact_uri)
  File "/opt/bitnami/python/lib/python3.10/site-packages/mlflow/store/artifact/gcs_artifact_repo.py", line 40, in __init__
    from google.auth.exceptions import DefaultCredentialsError
ModuleNotFoundError: No module named 'google.auth' 
```

### Additional information

As a work around we install `google-cloud-storage` over the image everytime the server is connected to, but would be good to have it in built in the image since it is core functionality. Would open a PR but not sure where to install this missing package in the repo.

This also seems related; https://github.com/bitnami/charts/issues/22720

### PR DESCRIPTION
**Pull request by dhrp**
### Description of the change

Updates the Bitnami MLFlow image to contain the google-cloud-storage pip module. 

### Benefits

This allows MLFlow to use the (built in) support for working with google cloud storage for storing and retrieving artifacts from google cloud storage. It is significant to run the MLFlow tracking server in this mode with google storage; but is also useful when using the MLFlow container in client mode.

### Possible drawbacks

None that I know; though I don't know if adding a pip install at the end is the approach desired by Bitnami. • An alternative approach would be to add it to the mlflow stacksmith tarball; but AFAIK I cannot contribute to that. Will let that to the maintainers. 

### Applicable issues

Add support onto the container: fixes: https://github.com/bitnami/containers/issues/65108
Add support to google cloud storage in the MLFlow chart: Relates to https://github.com/bitnami/charts/issues/22720

### Additional information

I'm happy to change approach if directed to how.

### CODE REVIEW

**Comment by juan131** [comment]
Hi @dhrp 

Thanks so much for this contribution!

We're currently evaluating the impact of including this Python module which seems to increase the image size by 16MB. We need to decide whether it's widely used or not before including it since we want the image to include only the most important modules and ask users to extend the image adding their custom ones for less important use cases.

In case we decide to accept it, please note it won't be included in the image using the "pip install" directive you proposed, but as part of the `mlflow-2.13.0-0-linux-${OS_ARCH}-debian-12.tar.gz` tarball added below:

- https://github.com/bitnami/containers/blob/main/bitnami/mlflow/2/debian-12/Dockerfile#L32

We'll keep you updated about any decision we take.

**Comment by dhrp** [comment]
Hi @juan131, ok; thanks for your message. 

It seems that at least two other people commented, and 4 👍 on my issue on the MLFlow Helm chart that they would like to have the feature. See: https://github.com/bitnami/charts/issues/22720

**Comment by juan131** [comment]
Hi @dhrp 

Thanks for the insights, I'll share with the team.

> Also: is there any way to see on contribute to how these tarballs are created?

I'm afraid the compilation recipes we use to build Bitnami assets are internal. We may consider moving them to some public repo since there's nothing to hide on them.

**Comment by juan131** [comment]
not stale

**Comment by dhrp** [comment]
Can we move this forward? I personally think the amount of 👍 (now 6) on the [MLflow chart](https://github.com/bitnami/charts/issues/22720) depending on this change is sufficient to make this change - if it's only a 16Mb size increase. -- As I see it storing models on a durable storage really is a primary feature of MLFlow.

**Comment by juan131** [comment]
Hi @dhrp 

I'm glad to confirm we got the "green light" to include this module by default in the image. I'm applying the required changes right now and I'll ping you once we released a new container image version including it.

**Comment by juan131** [comment]
Hi @dhrp 

Please give it a try using the image tag `2.14.1-debian-12-r1`

**Comment by juan131** [comment]
I'm closing this PR given we included the missing pip module in `2.14.1-debian-12-r1` revision, please reopen it if you require further assistance.

**Comment by dhrp** [comment]
HI @juan131, somehow didn't see this until now! Thanks so much of moving this forward. Very happy about it!

**Pull request closed without merging**
