### PR TITLE
[bitnami/dokuwiki] Deprecate dokuwiki

### PR DESCRIPTION
**Pull request by dgomezleon**
### Description of the change

Deprecate DokuWiki container.

### CODE REVIEW

**Review by fmulero — APPROVED** [review]
LGTM

**Comment by Donatas-L** [comment]
Is there any note of explanation as to why you decided to deprecate Dokuwiki support?

**Comment by carrodher** [comment]
> Is there any note of explanation as to why you decided to deprecate Dokuwiki support?

I understand your concern regarding this deprecation. DokuWiki has been deprecated from the Bitnami catalog because our focus has shifted towards infrastructure solutions. As a result, we are phasing out certain web application assets to better align with our strategic direction.

**Comment by splitbrain** [comment]
The official DokuWiki container is probably a good alternative: https://github.com/dokuwiki/docker

**Pull request merged**
