### PR TITLE
fix(pg-bouncer-env): remove asterisks

### LINKED ISSUE #54877: [bitnami/pgbouncer] Release 1.21.0-debian-11-r8 crashes after start with: invalid value "**0**" for parameter server_fast_close in configuration
### Name and Version

bitnami/pgbouncer:1.21.0-debian-11-r8

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Start pgbouncer container with not configured environment variable `PGBOUNCER_SERVER_FAST_CLOSE`.

### What is the expected behavior?

Use the default value of plain 0 in pgbouncer configuration for server_fast_close.

### What do you see instead?
```
ERROR invalid value "**0**" for parameter server_fast_close in configuration (/opt/bitnami/pgbouncer/conf/pgbouncer.ini:20)
FATAL cannot load config file
```

### PR DESCRIPTION
**Pull request by pmlk**
This removes the asterisks in the default value for `PGBOUNCER_SERVER_FAST_CLOSE` which causes an error: `Invalid value '**0**' for SERVER_FAST_CLOSE`

### Description of the change

replace default value `**0**` with `0`

### Benefits

No errors without overriding `PGBOUNCER_SERVER_FAST_CLOSE`.

### Possible drawbacks

None

### Applicable issues

- fixes: https://github.com/bitnami/containers/pull/54732#issuecomment-1898554105
- fixes https://github.com/bitnami/containers/issues/54877

### CODE REVIEW

**Review by derhuerst — APPROVED** [review]

**Comment by pmlk** [comment]
Since I submitted this I have found out that this wrong default value was automatically set here: https://github.com/bitnami/containers/commit/ae5a6307d7496102f9ff748f6a12cb2fdbbf7e0a

So this PR may not address the root cause of this. Beware.

**Comment by deedy5** [comment]
up

**Review by juan131 — APPROVED** [review]
Thanks for this fix! LGTM

**Comment by juan131** [comment]
I'll force a new container release, so there'll be a new `1.21.0-debian-11-r10` version addressing this

**Comment by derhuerst** [comment]
Now the release commit has removed the `0`. 😄

https://github.com/bitnami/containers/commit/284d2f7fdf37e95be78519e5d0aec7bb2f908df4#diff-bc45ea65cb6bb823813b9f0b1112768a0382363fb8df341559d7220ede30e464R130

**Comment by pmlk** [comment]
> Now the release commit has removed the `0`. 😄
> 
> [284d2f7#diff-bc45ea65cb6bb823813b9f0b1112768a0382363fb8df341559d7220ede30e464R130](https://github.com/bitnami/containers/commit/284d2f7fdf37e95be78519e5d0aec7bb2f908df4#diff-bc45ea65cb6bb823813b9f0b1112768a0382363fb8df341559d7220ede30e464R130)

Can't say I didn't post a warning about something like this 🙈 https://github.com/bitnami/containers/pull/54874#issuecomment-1898785232

**Comment by viceice** [comment]
so r11 version will be broken again?

**Comment by deedy5** [comment]
just add `PGBOUNCER_SERVER_FAST_CLOSE`
Something like
```python3
pgbouncer:
    image: docker.io/bitnami/pgbouncer:1
    ports:
      - 6432:6432
    volumes:
      - './userlists.txt:/bitnami/userlists.txt'
    environment:
      - POSTGRESQL_HOST=pg1
      - POSTGRESQL_PASSWORD=password1
      - POSTGRESQL_DATABASE=db1
      - PGBOUNCER_AUTH_TYPE=trust
      - PGBOUNCER_USERLIST_FILE=/bitnami/userlists.txt
      - PGBOUNCER_SERVER_FAST_CLOSE=0
```

**Comment by derhuerst** [comment]
@juan131 Can you give an estimate when an image will be published that doesn't require a workaround?

**Comment by juan131** [comment]
@derhuerst @pmlk @deedy5 @viceice the default value was fixed at `1.22.0-debian-11-r1` release, see:

- https://github.com/bitnami/containers/commit/6ab663653e542d208e188b0b8671cbfdb1676e95

**Pull request merged**
