### PR TITLE
[bitnami/pgbouncer] log to stdout only by default

### LINKED ISSUE #68508: [bitnami/pgbouncer] Option to disable writing logs to a file
### Name and Version

bitnami/pgbouncer:1.22.1

### What is the problem this feature will solve?

Current configuration forces pgbouncer logs to be written to the file, in addition to the stderr logging[^1].

https://github.com/bitnami/containers/blob/6c7d4f746072925abe987a3a3a6ad8962c89184b/bitnami/pgbouncer/1/debian-12/rootfs/opt/bitnami/scripts/pgbouncer-env.sh#L119-L120

This result in unnecessary `pgbouncer.log` which is taking a lot of the space on the local filesystem.

[^1]: > logfile
      > Specifies the log file. For daemonization (-d), either this or syslog need to be set.
      >
      > The log file is kept open, so after rotation, kill -HUP or on console RELOAD; should be done. On Windows, the service must be stopped and started.
      >
      > Note that setting logfile does not by itself turn off logging to stderr. Use the command-line option -q or -d for that.
      >
      > Default: not set
      > 
      > https://www.pgbouncer.org/config.html

### What is the feature you are proposing to solve the problem?

Introduce conditional check to add `logfile` entry to the ini file when 

```
PGBOUNCER_LOG_FILE=disable
```

### What alternatives have you considered?

_No response_

### PR DESCRIPTION
**Pull request by taraspos**
### Description of the change

~Add option to disable logging to file by setting `PGBOUNCER_LOG_FILE=disable`.~
Change default to log to stdout only (instead of stdout and file) by default.

### Benefits

pgbouncer is running in the foreground ([without the `-d` flag](https://github.com/taraspos/containers/blob/030d5a26fdb3e7d7633f5a8a3e96e4b172be7c8b/bitnami/pgbouncer/1/debian-12/rootfs/opt/bitnami/scripts/pgbouncer/run.sh#L21-L22)) mode so logs are written to stdout anyway.

When running on Kubernetes/ECS/etc this is enough and having same information in a logfile is unnecessary. From my experience this logfile can grow quite large and having option to disable can fix potential disk space problems.

`logfile` definition from [pgbouncer config documentation](https://www.pgbouncer.org/config.html): 
> ### Generic settings
> **logfile**
> Specifies the log file. For daemonization (-d), either this or syslog need to be set.
>
>The log file is kept open, so after rotation, kill -HUP or on console RELOAD; should be done. On Windows, the service must be stopped and started.
>
>Note that setting logfile does not by itself turn off logging to stderr. Use the command-line option -q or -d for that.
>
>Default: not set

### Possible drawbacks

N/A

### Applicable issues

- fixes #68508 

### Additional information

<details><summary>pgbouncer.ini with default PGBOUNCER_LOG_FILE value</summary>

```ini
[databases]
postgres=host=postgresql port=5432 dbname=postgres

[pgbouncer]
listen_port=6432
listen_addr=0.0.0.0
unix_socket_dir=/tmp/
unix_socket_mode=0777
auth_file=/opt/bitnami/pgbouncer/conf/userlist.txt
auth_type=scram-sha-256
pidfile=/opt/bitnami/pgbouncer/tmp/pgbouncer.pid
admin_users=postgres
client_tls_sslmode=disable
server_tls_sslmode=disable
ignore_startup_parameters=extra_float_digits
stats_period=60
server_round_robin=0
server_fast_close=0
```

</details>

<details><summary>pgbouncer.ini with PGBOUNCER_LOG_FILE=/tmp/test</summary>

```ini
[databases]
postgres=host=postgresql port=5432 dbname=postgres

[pgbouncer]
listen_port=6432
listen_addr=0.0.0.0
unix_socket_dir=/tmp/
unix_socket_mode=0777
auth_file=/opt/bitnami/pgbouncer/conf/userlist.txt
auth_type=scram-sha-256
pidfile=/opt/bitnami/pgbouncer/tmp/pgbouncer.pid
logfile=/tmp/test
admin_users=postgres
client_tls_sslmode=disable
server_tls_sslmode=disable
ignore_startup_parameters=extra_float_digits
stats_period=60
server_round_robin=0
server_fast_close=0
```

</details>

### CODE REVIEW

**Review by lancedikson — APPROVED** [review]
Would be nice to have this feature! LGTM! 👍

**Comment by taraspos** [comment]
@migruiz4 all done!

**Review by migruiz4 — APPROVED** [review]
Thank you very much!

**Comment by taraspos** [comment]
@migruiz4 thank you!
Is this ready to be merged now?

**Comment by lancedikson** [comment]
May I ask what the ETA for the release is? :)

**Comment by migruiz4** [comment]
I triggered a new release now, so in about 30 more minutes or so a new PR should be submitted, tested, and merged automatically if everything goes well. 
Shortly after the image should be available in Dockerhub as well.

**Comment by taraspos** [comment]
It's out 🎉 
- https://github.com/bitnami/containers/pull/69156

**Pull request merged**
