### PR TITLE
[bitnami/minio-client] add jq

### LINKED ISSUE #53709: include jq in minio-client image
### Name and Version

bitnami/minio-client

### What is the problem this feature will solve?

mc (minio-client) is able to output json for most commands,

so jq would be really useful to handle this output

### What is the feature you are proposing to solve the problem?

include jq in minio-client image

for [example](https://github.com/bitnami/containers/blob/main/bitnami/kubectl/1.28/debian-11/Dockerfile#L26), kubectl image include jq 

### What alternatives have you considered?

_No response_

### PR DESCRIPTION
**Pull request by jouve**
### Description of the change

add jq to minio-client image

### Applicable issues

- fixes #53709

### CODE REVIEW

**Comment by jouve** [comment]
any news ?

**Review by fevisera — APPROVED** [review]
Thank you for your contribution!
LGTM!

**Comment by jouve** [comment]
do you know when the image will be released ?

**Comment by fevisera** [comment]
Hi @jouve,

The new version of the container will be released as part of an automated process. I have reviewed the process, and it has experienced some delays due to recent internal changes in the platform, requiring more time than usual. Nevertheless, I anticipate that it will be published soon. I apologize for any inconvenience this may cause.

Thanks.

**Comment by fevisera** [comment]
Hi, 

Just confirming the `bitnami/minio-client` container with jq is already available:

```
$ docker run --rm -it bitnami/minio-client jq
 16:33:09.49 INFO  ==>
 16:33:09.49 INFO  ==> Welcome to the Bitnami minio-client container
 16:33:09.49 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers
 16:33:09.49 INFO  ==> Submit issues and feature requests at https://github.com/bitnami/containers/issues
 16:33:09.49 INFO  ==>

jq - commandline JSON processor [version 1.6]

Usage:	jq [options] <jq filter> [file...]
	jq [options] --args <jq filter> [strings...]
	jq [options] --jsonargs <jq filter> [JSON_TEXTS...]

jq is a tool for processing JSON inputs, applying the given filter to
its JSON text inputs and producing the filter's results as JSON on
standard output.

The simplest filter is ., which copies jq's input to its output
unmodified (except for formatting, but note that IEEE754 is used
for number representation internally, with all that that implies).

For more advanced filters see the jq(1) manpage ("man jq")
and/or https://stedolan.github.io/jq

Example:

	$ echo '{"foo": 0}' | jq .
	{
		"foo": 0
	}

For a listing of options, use jq --help.
```

**Comment by jouve** [comment]
Awesome, Thanks !

**Pull request merged**
