### PR TITLE
[bitnami/keycloak] Oracle Database Support

### LINKED ISSUE #21897: [bitnami/keycloak] Oracle database support for bitnami/keycloak
### Name and Version

bitnami/keycloak

### What is the problem this feature will solve?

You're writing explicitly the following in your README:

_The Bitnami Keycloak container requires a PostgreSQL database to work._

What does it mean exactly? It means, I can run your keycloak container only with a PostgreSQL database and with an Oracle database it's not working?

Many thanks for your feedback.

Best Regards,
Marco

### What is the feature you are proposing to solve the problem?

Support for Oracle database.

### What alternatives have you considered?

_No response_

### PR DESCRIPTION
**Pull request by m4rcoschmucki**
Adding possibility to connect to an Oracle database.

### Description of the change

With this change there is the possibility to connect the Keycloak to an Oracle database.

### Benefits

The integration of Keycloak is more flexibel. No need to have PostgreSQL, now also Oracle database is an option. 

### Possible drawbacks

To my knowledge no limitations with this change.

### Applicable issues

  - fixes #21897

### Additional information

1. It's my very first commit and pull request on github.com, so please be nice to me and understand it, when I do some basic steps wrong ;-) Thank you very much!

2. I was able to test my change successfully with the following Oracle database versions:

- 11gR2
- 19.3c
- 21.3c

### CODE REVIEW

**Comment by javsalgar** [comment]
Hi,

Thank you so much for the contribution! Could you fix the DCO issue?

**Comment by m4rcoschmucki** [comment]
Hi Javier

I did it just now!
I hope, I did it in the right way!?

Best regards,
Marco

**Comment by gongomgra** [comment]
Hi @m4rcoschmucki,

Thanks for using Bitnami and for sending this PR. We have been reviewing your changes and although the changes look good, we are not sure that adding support for Oracle databases is a good addition to our solution. We follow official guidelines from upstream developers for requirements and supported features in our products.

According to the official Keycloak article linked below, they consider Oracle database as a second class database, and they will stop providing official support for it in the long term. Furthermore, they encourage users to migrate to first class databases.

https://www.keycloak.org/2022/02/dbs.html

Our main concern is to miss the deprecation notice for Oracle databases and that it ends up affecting our users.

**Comment by m4rcoschmucki** [comment]
Hi @gongomgra 

Many thanks for your feedback.

Your point is a very good point and I was not aware of it.
Thank you for highlighting this.

Anyway, there's a lot of people which are using Keycloak with an Oracle database.
I'm really wondering how Keycloak will do this in the future (everyone needs to migrate from Oracle to i.e. PostgreSQL) ;-)

**Pull request closed without merging**
