### PR TITLE
[bitnami/discourse] Fix postgresql-client version mismatch

### LINKED ISSUE #9830: Discourse backup fails due to mismatch in pg_dump versions
### Name and Version

bitnami/discourse 7.0.15

### What steps will reproduce the bug?

1. Backup Discourse using native admin tool
2. Upgrade discourse Helm chart version 5.2.3 to 7.0.15
3. Restore data using native admin tool.
4. Attempt to run a new backup.

### Are you using any custom parameters or values?

```yaml
diagnosticMode:
  enabled: false
host: "forum.example.com"
siteName: "My Forum"
auth:
  email: "admin@example.com"
  username: "admin"
  existingSecret: "discourse-admin"
smtp:
  enabled: true
  host: "smtp.example.com"
  port: "25"
replicaCount: 3

discourse:
  skipInstall: true
persistence:
  enabled: true
  storageClass: "-"
  accessModes:
    - ReadWriteMany
  accessMode: ReadWriteMany
  size: 15Gi
  existingClaim: "discourse-data-0-pvc"
ingress:
  enabled: false
postgresql:
  enabled: true
  auth:
    enablePostgresUser: true
    postgresPassword: bitnami
    username: bn_discourse
    password: ""
    database: bitnami_application
    existingSecret: "discourse-db"
  architecture: standalone
  global:
    storageClass: "longhorn"
    postgresql:
      auth:
        existingSecret: "discourse-db"
  primary:
    persistence:
      existingClaim: "discourse-postgresql-pvc"
redis:
  enabled: true
  auth:
    enabled: true
    password: ""
    existingSecret: "discourse-redis"
    auth:
      existingSecret: "discourse-redis"
      existingSecretPasswordKey: "redis-password"
  architecture: standalone
  master:
    persistence:
      enabled: false
```

### What is the expected behavior?

The backup should execute properly.

### What do you see instead?

The backup fails with
```
...
[2022-04-19 16:40:13] Marking backup as running...
[2022-04-19 16:40:13] Making sure '/opt/bitnami/discourse/tmp/backups/default/2022-04-19-164012' exists...
[2022-04-19 16:40:13] Making sure '/opt/bitnami/discourse/public/backups/default' exists...
[2022-04-19 16:40:13] Updating metadata...
[2022-04-19 16:40:13] Dumping the public schema of the database...
[2022-04-19 16:40:13] pg_dump: error: server version: 14.2; pg_dump version: 13.6
[2022-04-19 16:40:13] pg_dump: error: aborting because of server version mismatch
[2022-04-19 16:40:13] EXCEPTION: pg_dump failed
...
```

### Additional information

The currently running images are:

* `docker.io/bitnami/discourse:2.8.3-debian-10-r0`
* `docker.io/bitnami/postgresql:14.2.0-debian-10-r58`

### PR DESCRIPTION
**Pull request by karpfediem**
### Description of the change

This updates the postgresql-client version.

### Benefits

Allows to use the backup functionality that relies on the postgresql-client being up to date again.

### Applicable issues

  - fixes https://github.com/bitnami/charts/issues/9830

### CODE REVIEW

**Comment by fmulero** [comment]
Thanks for creating this PR. Please, note it is needed to sign the commits. Your signature certifies that you wrote the patch or otherwise have the right to contribute the material. You can find more info about this topic, in [the “Sign your work” section from the contributing guidelines](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#sign-your-work). For this particular PR you can find more details attached to the [DCO check](https://github.com/bitnami/containers/pull/4458/checks?check_run_id=8076774252)

Also, could you fix the conflicts?

**Comment by karpfediem** [comment]
> Thanks for creating this PR. Please, note it is needed to sign the commits. Your signature certifies that you wrote the patch or otherwise have the right to contribute the material. You can find more info about this topic, in [the “Sign your work” section from the contributing guidelines](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#sign-your-work). For this particular PR you can find more details attached to the [DCO check](https://github.com/bitnami/containers/pull/4458/checks?check_run_id=8076774252)
> 
> Also, could you fix the conflicts?

Got a bit confused using the wrong git remote, should be fine now.
I also came across https://github.com/bitnami/containers/blob/5a56fb8ef2a2c688c9227324a27293321aaf9cea/bitnami/discourse/2/debian-11/prebuildfs/opt/bitnami/.bitnami_components.json#L35
Not sure if this is automated, or which locations need additional manual updating

**Comment by karpfediem** [comment]
sha256 for amd64 is missing
https://downloads.bitnami.com/files/stacksmith/postgresql-client-14.5.0-0-linux-amd64-debian-11.tar.gz.sha256

**Comment by karpfediem** [comment]
Can i do anything to speed this up? This should be a very simple change, as well as simple to review.

The currently downloaded postgresql client is simply out of date by a few versions.

It seems like i picked a bad time, getting a ton of new conflicts while you are changing the overall structure of installing dependencies.
I will wait until i get any response for the next conflicts. Please let me know how to proceed with this.

**Comment by karpfediem** [comment]
Stale due to missing review

**Review by fmulero — APPROVED** [review]
Thanks a lot for your contribution @karpfediem and sorry for my very late response.

We had several internal discussions about this topic due to [this thread](https://meta.discourse.org/t/any-chance-to-upgrade-the-postgres-client-version/215063)

Because this asset is a community supported solution, this is an external contribution and our tests didn't find any particular issue, we have decided to accept the changes

**Pull request merged**
