### PR TITLE
[bitnami/gitea] Add new customizable environment variables - ENABLE OPENID SIGNIN/SIGNUP

### PR DESCRIPTION
**Pull request by ikamii**
[bitnami/gitea] Add new customizable environment variables

                1. ENABLE_OPENID_SIGNIN (default: false)
                2. ENABLE_OPENID_SIGNUP (default: false)

### Description of the change

I have made changes in scripts `gitea-env.sh`, `libgitea.sh` and in `app.ini.template` to add two new customizable environment variables.

### Benefits

Users can enable `OpenID sign in` and `OpenID sign up` if necessary. ( I might use it for signing in via Keycloak for example.)

### Applicable issues

https://github.com/bitnami/charts/issues/25572

I will also make changes in bitnami/charts - gitea to enable the same feature for the helm chart.

### CODE REVIEW

**Comment by ikamii** [comment]
I did the second push to sign the commit because I forgot to change the gpg.

**Comment by ikamii** [comment]
Okay I found an error.

After setting the values to true the container starts with the right values.
I get 
```sh
[openid]
ENABLE_OPENID_SIGNIN = true
ENABLE_OPENID_SIGNUP = true
```

after a while both turns to false (gitea auto assigns the values).

And after I restart the container it turns to the values which I set again.

I couldn't find how to solve this. Do you have any idea?

Thanks in advance.

**Review by dgomezleon — DISMISSED** [review]

**Comment by dgomezleon** [comment]
> Okay I found an error.
> 
> After setting the values to true the container starts with the right values. I get in `app.ini`
> 
> ```ini
> [openid]
> ENABLE_OPENID_SIGNIN = true
> ENABLE_OPENID_SIGNUP = true
> ```
> 
> after fully gitea initialization, both turns to false (gitea auto assigns the values to `false).
> 
> And after I restart the container it turns to the values which I set again.
> 
> I couldn't find how to solve this. Do you have any idea?
> 
> Thanks in advance.

I didn't see your comment until now. I will check as soon as I can.

**Comment by ikamii** [comment]
Hi again, 

I have found the solution thanks to @javsalgar. 

When I set the values after `gitea_pass_wizard` function it works.

I am going to commit the changes asap.

**Review by dgomezleon — APPROVED** [review]
Thanks for checking it. LGTM

**Pull request merged**
