### PR TITLE
bump java from 17 to 21

### PR DESCRIPTION
**Pull request by achraf-mer**
### Description of the change

Upgrade java to latest.

### Benefits

Use the latest version to extend EOL support date for java.

### Possible drawbacks

Possible unknown failures or incompatibilites.

### CODE REVIEW

**Comment by achraf-mer** [comment]
@carrodher my first attempt to update in this repo, please feel free to point out if any steps/requirements are missing to get the build going. 
Thank you!

**Comment by carrodher** [comment]
Thanks for your contribution. Please note this kind of change need to be implemented in our internal test & release pipeline. Being said that, I'm moving to _In progress_ this PR so the team can evaluate and perform the required changes.

**Comment by Mauraza** [comment]
Hi @achraf-mer,

Thanks for the contribution! I will running some test and I come back when I have more information.

**Comment by Mauraza** [comment]
Hi @achraf-mer,

Could you resolve the conflicts?

**Comment by achraf-mer** [comment]
> Hi @achraf-mer,
> 
> Could you resolve the conflicts?

done.

**Comment by Mauraza** [comment]
please, could you sign the commit?:
```
git rebase HEAD~2 --signoff
git push --force-with-lease origin am/upgrade_java
```

**Pull request closed without merging**
