### PR TITLE
[bitnami/cassandra] broadcast_rpc_address via env

### LINKED ISSUE #63704: [bitnami/cassandra] Cassandra broadcast_rpc_address via ENV Settings
### Name and Version

bitnami/cassandra:4.1.3

### What is the problem this feature will solve?

Currently I can configure many settings using the environment variables. This does work fine. But this is not possible for all Cassandra settings. One of them is the `broadcast_rpc_address`, which ist not included in the environmental setup.

### What is the feature you are proposing to solve the problem?

Currently, the `broadcast_rpc_address` will be automatically set to the content of the `host ` variable
https://github.com/bitnami/containers/blob/65e6858935df67a71fe056538476e42abf405cbf/bitnami/cassandra/4.1/debian-12/rootfs/opt/bitnami/scripts/libcassandra.sh#L405
which in turn will be 127.0.0.1 or the docker containers ip, depending on the state of the `CASSANDRA_ENABLE_REMOTE_CONNECTIONS` environment variable. I would like to set this value manually to reflect the public ip of the host machine.

I cannot use the `CASSANDRA_HOST` variable, as this value will also be used for the cassandra setting `listen_address`, which should not be the hosts public ip but the container ip. 

### What alternatives have you considered?

My Configuration does work fine if I use the configuration file `cassandra.yaml` as described in the containers readme. Nevertheless, I would prefer the way of configuring the container using environmental variables, including the `broadcast_rpc_address`.

### PR DESCRIPTION
**Pull request by tobiasbhn**
### Description of the change
The Cassandra setting `broadcast_rpc_address` could previously not be changed via an environment variable, many other settings are already implemented to be configured via env vars. The mentioned setting is currently only changeable using a mounted `cassandra.yaml` settings file.

The changes made in this PR implemented a new environmental variable called `CASSANDRA_BROADCAST_RPC_ADDRESS`. This environmental variable is implemented in the same way as its 'big brother' (`CASSANDRA_BROADCAST_ADDRESS`).

### Benefits
This variable allows the custom configuration of the `broadcast_rpc_address` without the use of an explicit `cassandra.yaml`.

### Applicable issues
- Fixes #63704

### Additional information
The changes were built locally (https://hub.docker.com/r/tobiasbhn/cassandra) and tested using the following configuration (shortened for demonstration purposes):
```yaml
  cassandra:
    image: tobiasbhn/cassandra:latest
    ports: [7000:7000,9042:9042]
    environment:
      CASSANDRA_CLUSTER_NAME: cassandra-cluster
      CASSANDRA_BROADCAST_ADDRESS: 192.168.0.238
      CASSANDRA_BROADCAST_RPC_ADDRESS: 192.168.0.238
```

When starting Cassandra and running `nodetool gossipinfo`, the following information is returned:
```
/192.168.0.238
  ....... (other infos)
  RELEASE_VERSION:6:4.1.4
  RPC_ADDRESS:5:192.168.0.238
  NET_VERSION:2:12
  HOST_ID:3:341e5794-c8e7-468c-a5f1-661e1dfba676
  RPC_READY:31:true
  NATIVE_ADDRESS_AND_PORT:4:192.168.0.238:9042  <--- this is configured via env as proposed in this pr
  STATUS_WITH_PORT:18:NORMAL,-1047668167520589689
  .... other infos
```

### CODE REVIEW

**Comment by tobiasbhn** [comment]
Edit: I have not enhanced the README to include the variable `CASSANDRA_BROADCAST_RPC_ADDRESS` in the README. This is because the already existend variable `CASSANDRA_BROADCAST_ADDRESS` is also not mentioned. Perhaps both variables should also be included?

**Comment by dgomezleon** [comment]
> Edit: I have not enhanced the README to include the variable `CASSANDRA_BROADCAST_RPC_ADDRESS` in the README. This is because the already existend variable `CASSANDRA_BROADCAST_ADDRESS` is also not mentioned. Perhaps both variables should also be included?

Hi @tobiasbhn ,

Good catch. Yes, both should appear in the README.md. Could you please add them?

The rest of the changes LGTM. Thanks for contributing.

**Comment by dpavlov-smartling** [comment]
Hello @tobiasbhn recently my PR https://github.com/bitnami/containers/pull/63358 was merged and it should solve your issue and similar one. Please check it out.
Thanks,

**Comment by tobiasbhn** [comment]
@dgomezleon I added both vars to the readme.
@dpavlov-smartling Thank you, I will take a look at your PR.

**Comment by dgomezleon** [comment]
Thanks @tobiasbhn ,

With the mentioned [PR](https://github.com/bitnami/containers/pull/63358), it would not be necessary to add 

```
        if [[ -n "$CASSANDRA_BROADCAST_RPC_ADDRESS" ]]; then
            cassandra_yaml_set "broadcast_rpc_address" "$CASSANDRA_BROADCAST_RPC_ADDRESS"
        fi
```

since it would be added by `cassandra_setup_from_environment_variables` function.

**Comment by tobiasbhn** [comment]
@dgomezleon I partly agree. I have looked into the PR and it does indeed fix this and all future config issues. But wouldn’t it be consistent to have the basic and most used settings explicit available, like the other env settings? Otherwise, except of backwards compatibility, all other env settings could theoretically and should eventually be removed.

But as this is a design decision I’d leave it up to you. You can close this issue if you decide against this var.

**Pull request closed without merging**
