### PR TITLE
[bitnami/postegresql-repmgr] Added missing postgresql environment variables

### PR DESCRIPTION
**Pull request by dcamarenaAZO**
### Description of the change

Added missing postgresql environment variables regarding connections to README.md

### Benefits

Developers can see them without looking into the code. 

### Possible drawbacks

None

### Applicable issues

- workarround for #52130

### Additional information

POSTGRESQL_EXTRA_FLAGS is ignored and it is not possible to pass start parameters to PostgreSQL server.

### CODE REVIEW

**Comment by Mauraza** [comment]
Hi @dcamarenaAZO,

Thanks for the contribution! To add environment variables, you need to add them in all postgresql-env.sh.
Could you update this PR with those changes?

**Comment by dcamarenaAZO** [comment]
> Hi @dcamarenaAZO,
> 
> Thanks for the contribution! To add environment variables, you need to add them in all postgresql-env.sh. Could you update this PR with those changes?

Hi @Mauraza, 

thank you for your answer. Did you have a look at [version 11 postgresql-env.sh](https://github.com/bitnami/containers/blob/f2ce94b2977cb536585d29328f3f3da4fdc4852d/bitnami/postgresql-repmgr/11/debian-11/rootfs/opt/bitnami/scripts/postgresql-env.sh#L192C5-L192C5)? 
In [version-12](https://github.com/bitnami/containers/blob/f2ce94b2977cb536585d29328f3f3da4fdc4852d/bitnami/postgresql-repmgr/12/debian-11/rootfs/opt/bitnami/scripts/postgresql-env.sh#L192C18-L192C18), [13](https://github.com/bitnami/containers/blob/f2ce94b2977cb536585d29328f3f3da4fdc4852d/bitnami/postgresql-repmgr/13/debian-11/rootfs/opt/bitnami/scripts/postgresql-env.sh#L192C19-L192C19), [14](https://github.com/bitnami/containers/blob/f2ce94b2977cb536585d29328f3f3da4fdc4852d/bitnami/postgresql-repmgr/14/debian-11/rootfs/opt/bitnami/scripts/postgresql-env.sh#L192C12-L192C12), [15](https://github.com/bitnami/containers/blob/f2ce94b2977cb536585d29328f3f3da4fdc4852d/bitnami/postgresql-repmgr/15/debian-11/rootfs/opt/bitnami/scripts/postgresql-env.sh#L192C20-L192C20) and [16](https://github.com/bitnami/containers/blob/f2ce94b2977cb536585d29328f3f3da4fdc4852d/bitnami/postgresql-repmgr/16/debian-11/rootfs/opt/bitnami/scripts/postgresql-env.sh#L192C13-L192C13) they are also present. 

As I stated in the PR, the variables were just missing in the documentation of [bitnami/postegresql-repmgr](https://github.com/bitnami/containers/tree/f2ce94b2977cb536585d29328f3f3da4fdc4852d/bitnami/postgresql-repmgr). They are already in the postgresql-env.sh. Technically everything worked. It was just a lack of documentation. 

Thanks for your effort. Let me know if you need anything else. 

Another question: I'm just using version 15.4. I just saw that [version 16 of bitnami/postgresql-repmgr was released on docker hub](https://hub.docker.com/r/bitnami/postgresql-repmgr/tags). Can you tell me where I can find the release notes, changelog or something to know about changes or compatibility from 15.4 to 16? 

Thanks, Cheers, Daniel

**Comment by dcamarenaAZO** [comment]
The pull request is just adding some missing environment variables to the documentation.

**Review by Mauraza — APPROVED** [review]
Hi @dcamarenaAZO,

Thanks for the contribution! LGTM!!

**Pull request merged**
