### PR TITLE
[bitnami/ejbca] Extend initial CA cert configs

### PR DESCRIPTION
**Pull request by Synertry**
Signed-off-by: Synertry <jonny.somrak@gmail.com>

### Description of the change

Extends the initial CA cert configurations.
At the moment the libejbca.sh script hard sets the initial ca cert configuration for this fields:
- Keytype (RSA)
- Keyspec (3072)
- Validity (3652)
- Policy (null)
- Signature Algorithm (SHA256WithRSA)

Default values have been taken from the hardcoded values before the change.

### Benefits

This code change allows to set those fields like the other environment variables.

### Possible drawbacks

User misconfigurations are possible, if an inappropiate value for an environment variable has been set e.g.:
EJBCA_CA_KEYSPEC: 123a

### Applicable issues

Non. It is a feature commit.

### Additional information

Configurable environment variables have been added to README.md

### CODE REVIEW

**Review by migruiz4 — APPROVED** [review]
Thank you very much for your contribution, looks good to me!

**Comment by Synertry** [comment]
Thanks for accepting it. But unfortunately the automated pr #14732 reverted the contribution.

**Comment by migruiz4** [comment]
I'm very sorry for the inconvenience, an already-in-progress release overrode the changes.

The changes were later restored in https://github.com/bitnami/containers/pull/15105

**Comment by Synertry** [comment]
It's ok no need to be sorry :)
And thanks for fixing it @migruiz4
Your automation and scripts are astounding 💯

**Pull request merged**
