### PR TITLE
[bitnami/redis-cluster] fix: Fixed redis-cluster support RDB persistence mode parameters

### PR DESCRIPTION
**Pull request by huangjc7**
### Benefits

Added REDIS_RDB_ENABLED and REDIS_RDB_POLICY environment variable parameters, which can freely open and close the RDB persistent policy

### CODE REVIEW

**Comment by huangjc7** [comment]
@javsalgar Hello, I need to explain this, it was reviewed by `CeliaGMqrz` before, but I am sorry that the content of my fork branch has been updated. Now I have re-forked the latest branch and completed the changes. Please review this is the previous pr request link `https://github.com/bitnami/containers/pull/23936`

**Comment by huangjc7** [comment]
@CeliaGMqrz Please check it again, thank you

**Review by CeliaGMqrz — APPROVED** [review]
Hi @huangjc7, Great :)
Thanks for your contribution! 
LGTM!

**Comment by dogzzdogzz** [comment]
Found issue #37522 in this PR

**Pull request merged**
