### PR TITLE
[bitnami/symfony] fix: added missing environment variable to symfony docker-compose.yml

### LINKED ISSUE #48437: /opt/bitnami/scripts/libsymfony.sh: line 39: !1: unbound variable
### Name and Version

bitnami/symfony:6.3

### What architecture are you using?

arm64

### What steps will reproduce the bug?

```bash
mkdir ~/myapp && cd ~/myapp
curl -LO https://raw.githubusercontent.com/bitnami/containers/main/bitnami/symfony/docker-compose.yml
docker-compose up
```

### What is the expected behavior?

Running image.

### What do you see instead?
```
symfony-myapp-1    | /opt/bitnami/scripts/libsymfony.sh: line 39: !1: unbound variable
symfony-myapp-1 exited with code 1
```

### PR DESCRIPTION
**Pull request by JefvdA**
### Description of the change

As mentioned in the [referenced ticket](https://github.com/bitnami/containers/issues/48437) there was a missing environment variable. `SYMFONY_PROJECT_SKELETON` was not set in the docker-compose.yaml for symfony.

This change adds the missing environment variable. 

`SYMFONY_PROJECT_SKELETON=symfony/skeleton` -> it is set to `symfony/skeleton` which should be the correct value as mentioned in the [referenced issue](https://github.com/bitnami/containers/issues/48437)

### Benefits
When merging this the error thrown from [48437](https://github.com/bitnami/containers/issues/48437) won't be thrown again :)

### Applicable issues

- fixes #48437

### CODE REVIEW

**Review by joancafom — CHANGES_REQUESTED** [review]
Hi @JefvdA ! Thanks for your contribution. 

Although the error message does not show when this is defined in the `docker-compose.yml` filde (and this should suffice), I believe that in order to address it we should go down to the root issue: the variable `SYMFONY_PROJECT_SKELETON` is not defined in [symfony-env.sh](https://github.com/bitnami/containers/blob/main/bitnami/symfony/6.3/debian-11/rootfs/opt/bitnami/scripts/symfony-env.sh)

Defining it there (and setting a default value) would make that no matter if you use a docker-compose set up or the image alone, the error does not show anymore :) Could you please change this?

**Comment by JefvdA** [comment]
Hey @joancafom ! Thanks for the review, I had quite a busy week and only see it now. 

Sounds logical what you suggest, I'll update the PR as needed.

**Comment by JefvdA** [comment]
@joancafom I updated the `symfony-env.sh` for both the `5.4` and the `6.3` setup. I also tested locally by building the image and running it, and it succeeded.

I hard-coded the `SYMFONY_SKELETON` variable to `symfony/skeleton` in the `symfony-env.sh` file, to my knowledge there were no alternatives needed, right?

But if so, I'll make the variables overwritable and keeping `symfony/skeleton` as a default.

**Comment by joancafom** [comment]
Hi @JefvdA, thanks for your changes :) 

> I hard-coded the SYMFONY_SKELETON variable to symfony/skeleton in the symfony-env.sh file, to my knowledge there were no alternatives needed, right?

I've just checked and there are alternatives, though. Hence, I have slightly tweaked both approaches you already performed and combined them.

Now the default project is `symfony/skeleton` when using the `docker-compose` set-up, but it is not hardcoded (as other values are possible). Someone can just easily change that, and if no value is provided, a nice error message is shown now:

```
...
debian-11-myapp-1    | symfony 12:12:57.69 INFO  ==> Validating settings in SYMFONY_* environment variables...
debian-11-myapp-1    | symfony 12:12:57.69 ERROR ==> SYMFONY_PROJECT_SKELETON must be set
```

**Review by joancafom — APPROVED** [review]

**Pull request merged**
