### PR TITLE
[bitnami/postgresql] Introduces environment variable POSTGRESQL_DEFAULT_TRANSACTION_ISOLATION to change the global default transaction isolation level

### LINKED ISSUE #25013: [bitnami/postgresql] Unable to set Postgresql config flag with POSTGRESQL_EXTRA_FLAGS if the value contains space
### Name and Version

bitnami/postgresql:15.2.0

### What steps will reproduce the bug?

Run `docker run -e POSTGRESQL_DATABASE=foo -e POSTGRESQL_USERNAME=foo -e POSTGRESQL_PASSWORD=foo -e POSTGRESQL_EXTRA_FLAGS="-c default_transaction_isolation='read committed'" bitnami/postgresql` 

### What is the expected behavior?

I would expect to be able to set `default_transaction_isolation` even if the value contains a space, either by quoting it like in the reproduction or escaping the space or something. Maybe it's possible and I'm just missing something very obvious, but I can't figure it out.

### What do you see instead?

Fails with:
```
2023-02-23 16:37:36.352 GMT [1] FATAL:  invalid value for parameter "default_transaction_isolation": "'read"
2023-02-23 16:37:36.352 GMT [1] HINT:  Available values: serializable, repeatable read, read committed, read uncommitted.
```

### Additional information

The parsing happens at https://github.com/bitnami/containers/blob/218f5378c1d0c961078108981215ffed53092091/bitnami/postgresql/15/debian-11/rootfs/opt/bitnami/scripts/postgresql/run.sh#L19-L22. Looks like it's just splitting on space and also disabling backslash escapes.

### PR DESCRIPTION
**Pull request by cowclaw**
### Description of the change

The change introduces a new environment variable `POSTGRESQL_DEFAULT_TRANSACTION_ISOLATION` to the bitnami postgres images. The environment variable can be used to change the global default for the transaction isolation level in postgresql.

The change fixes https://github.com/bitnami/containers/issues/25013

It's currently not possible to change the default transaction isolation level using the `POSTGRESQL_EXTRA_FLAGS` if the desired isolation level's name contains a space.

https://github.com/bitnami/containers/blob/218f5378c1d0c961078108981215ffed53092091/bitnami/postgresql/15/debian-11/rootfs/opt/bitnami/scripts/postgresql/run.sh#L19-L22

If we'd omit the `-r` flag given to read in it would work with escaping the space in "repeatable read" with a backslash (`repeatable\ read`). However that this is not possible to preserve backwards compatibility since it could break existing solutions. 

### Benefits

It preserves backwards compatibility but still offers a possibility to change the global default transaction isolation level.

### Possible drawbacks

It does not use the existing environment variable `POSTGRESQL_EXTRA_FLAGS`.

### Applicable issues

--

### Additional information

I verified the change is correct using the below method.

For each folder in

- bitnami/postgresql/11/debian-11/
- bitnami/postgresql/12/debian-11/
- bitnami/postgresql/13/debian-11/
- bitnami/postgresql/14/debian-11/
- bitnami/postgresql/15/debian-11/

do

``` shell
docker build -t postgres_tmp .
``` 

``` shell
docker run -eALLOW_EMPTY_PASSWORD=yes --rm --name postgresql postgres_tmp
echo "SELECT current_setting('transaction_isolation');" | docker exec -i postgresql psql postgres postgres 

 current_setting 
-----------------
 read committed
(1 row)
```

``` shell
docker run -ePOSTGRESQL_DEFAULT_TRANSACTION_ISOLATION="repeatable read" -eALLOW_EMPTY_PASSWORD=yes --rm --name postgresql postgres_tmp 
echo "SELECT current_setting('transaction_isolation');" | docker exec -i postgresql psql postgres postgres 

 current_setting 
-----------------
 repeatable read
(1 row)
```

### CODE REVIEW

**Review by rafariossaa — CHANGES_REQUESTED** [review]
Hi,
  Thanks for adding this.
  This new environment variable should be also added to [postgresql-env.sh](https://github.com/bitnami/containers/blob/main/bitnami/postgresql/15/debian-11/rootfs/opt/bitnami/scripts/postgresql-env.sh)

**Comment by cowclaw** [comment]
Hi @rafariossaa 

Thanks for the review. 

I updated [postgresql-env.sh](https://github.com/bitnami/containers/blob/main/bitnami/postgresql/15/debian-11/rootfs/opt/bitnami/scripts/postgresql-env.sh) in df9866a0aca4c295ef7ecbff5a345458022eae0e

**Review by rafariossaa — APPROVED** [review]
LGTM

**Review by rafariossaa — APPROVED** [review]
LGTM

**Pull request merged**
