### PR TITLE
[bitnami/opencart] Fix opencart urls on OPENCART_ENABLE_HTTPS=true

### PR DESCRIPTION
**Pull request by iliyan-velichkov**
A fix for https://github.com/bitnami/charts/issues/21322

### CODE REVIEW

**Comment by iliyan-velichkov** [comment]
@fevisera did you get a change to check this PR?

**Comment by iliyan-velichkov** [comment]
any updates?

**Comment by iliyan-velichkov** [comment]
@javsalgar can you assign someone else to this issue?

**Comment by iliyan-velichkov** [comment]
please review this PR

**Review by fevisera — APPROVED** [review]
Thank you for your contribution!
LGTM!

**Pull request merged**
