### PR TITLE
[bitnami/redis-cluster] Fixed incorrect words and added examples

### PR DESCRIPTION
**Pull request by huangjc7**
Fixed RDB word
Added example of using REDIS_RDB_POLICY

REDIS_RDB_POLICY parameter If you want to use a special parameter, make a separate usage example, otherwise it will be difficult to use this parameter

### CODE REVIEW

**Comment by huangjc7** [comment]
@carrodher

**Comment by huangjc7** [comment]
@jotamartos

**Comment by huangjc7** [comment]
@jotamartos  Hello, can you guys take care of this?

**Review by jotamartos — APPROVED** [review]
Thanks for taking the time to create this PR. I just reviewed it and updated our internal systems. I made some minor changes related to the registered symbol we need to include in the README due to legal reasons and also added this information to the Redis' README. These changes will be available during the next release. 

Thanks

**Pull request merged**
