### PR TITLE
[bitnami/pgbouncer] make server_fast_close configurable via env var

### PR DESCRIPTION
**Pull request by derhuerst**
### Description of the change

This PR merely adds an env var `$PGBOUNCER_SERVER_FAST_CLOSE` to control [pgbouncer's `server_fast_close` config](https://www.pgbouncer.org/config.html#server_fast_close).

### Benefits

`server_fast_close` is necessary to "force-reload" clients connected via long-running connections when running with `pool_mode = session`.

### Possible drawbacks

What happens if `$PGBOUNCER_SERVER_FAST_CLOSE` is unset, null or empty?

### CODE REVIEW

**Review by Mauraza — COMMENTED** [review]
Hi @derhuerst,

Thanks for the contribution! 
To add an environmental variable you need to add it too in the file `pgbouncer-env.sh`

**Review by Mauraza — APPROVED** [review]
Hi @derhuerst ,

Thanks again for the contribution!! This change will be available in the next revision!!

**Comment by derhuerst** [comment]
@Mauraza Can you tell someone to take care of the [GitHub Action failing once an hour](https://github.com/derhuerst/bitnami-containers/actions/workflows/clossing-issues.yml), which sends me notifications (including email) that I cannot mute?

**Comment by Mauraza** [comment]
We are on it, but maybe you can unsubscribe from the PR.

**Comment by pmlk** [comment]
> What happens if $PGBOUNCER_SERVER_FAST_CLOSE is unset, null or empty?

This change seems to have broken one of our deployments where we use the latest image due to an invalid value (not set) for this environment variable. We quickly fixed it by setting `PGBOUNCER_SERVER_FAST_CLOSE=0`. Can this be set as the default value in the image to prevent others from running into this same issue once they redeploy with `latest`?

**Comment by carrodher** [comment]
Thank you for opening this issue and submitting the associated Pull Request. Our team will review and provide feedback. Once the PR is merged, the issue will automatically close.

Your contribution is greatly appreciated!

**Comment by derhuerst** [comment]
>> Can you tell someone to take care of the [GitHub Action failing once an hour](https://github.com/derhuerst/bitnami-containers/actions/workflows/clossing-issues.yml), which sends me notifications (including email) that I cannot mute?
>
> We are on it, but maybe you can unsubscribe from the PR.

That didn't help. It's been >150 notifications now, which AFAIK I cannot effectively mute or ignore.

**Pull request merged**
