### PR TITLE
[bitnami/pgpool] #28609: Added back missing library libnss-ldapd for fixing LDAP authentication.

### LINKED ISSUE #28609: [bitnami/pgpool] LDAP authentication not working - missing lib libnss_ldap.so.2
### Name and Version

bitnami/pgpool:4.4.2

### What architecture are you using?

arm64

### What steps will reproduce the bug?

Enabling LDAP authentication in the postgres-ha Helm chart does not work as the required library `libnss-ldapd` has been removed since `bitnami/pgpool:4.3.3-debian-11-r9` [PR #6507](https://github.com/bitnami/containers/pull/6507).

### What is the expected behavior?

LDAP authentication works, no error is logged.

### What do you see instead?

`nslcd: Warning: NSS_LDAP module not loaded: libnss_ldap.so.2: cannot open shared object file: No such file or directory`

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by olivergregorius**
### Description of the change 

Added back missing library libnss-ldapd for fixing LDAP authentication.

### Benefits

Fixing LDAP authentication

### Possible drawbacks

N/A

### Applicable issues

- fixes #28609 

### Additional information

N/A

### CODE REVIEW

**Comment by gongomgra** [comment]
Hi @olivergregorius,

Thanks for using Bitnami and for creating the PR. Although your changes are petty simple and I don't see any major issue with them, we need to double-check this internally in order to ensure it won't break any of other workflows related to pgpool. I'm moving the PR to on-hold status to avoid the stale bot to close it due to inactivity while our team work on this. 

We will get back to you on this when we have any update.

**Comment by olivergregorius** [comment]
Hi @gongomgra , any news on this topic?

**Comment by gongomgra** [comment]
Hi @olivergregorius,

Unfortunately, our engineering team didn't have the time to check this. I'm moving this back to "on-hold" status to avoid the stale bot to close this by mistake. Sorry for the inconveniences.

**Comment by olivergregorius** [comment]
@CeliaGMqrz Sure, done.

**Review by gongomgra — APPROVED** [review]

**Review by CeliaGMqrz — APPROVED** [review]
LGTM, Thanks for your contribution!

**Pull request merged**
