### PR TITLE
[bitnami/pgbouncer] Add auth_dbname to available environment variables

### PR DESCRIPTION
**Pull request by bayandin**
### Description of the change

Add `PGBOUNCER_AUTH_DBNAME` env variable, which translates into `auth_dbname ` PgBouncer config parameter.

### Benefits

It allows to configure `auth_dbname`

### Possible drawbacks

None, it's disabled by default.

### Applicable issues

None

### Additional information

PgBouncer 1.19 has introduced `auth_dbname` parameter, see https://www.pgbouncer.org/config.html#auth_dbname.
I've added it everywhere where a `PGBOUNCER_AUTH_DBNAME` is in use.

### CODE REVIEW

**Comment by bayandin** [comment]
Hey @aoterolorenzo, is there anything I can do to get this PR merged?

**Comment by bayandin** [comment]
Nope, the PR still makes sense

**Comment by aoterolorenzo** [comment]
Hey @bayandin ,

Sorry for the delay, complete missed this case. Let me take a look.

**Review by aoterolorenzo — APPROVED** [review]
LGTM

**Comment by bayandin** [comment]
Hey @aoterolorenzo, no problem! 
Thanks for merging this ❤️

**Comment by B-Galati** [comment]
@bayandin @aoterolorenzo Cannot see the feature in `main` branch sadly. Anything happened in between that would explain it?

**Pull request merged**
