### PR TITLE
[bitnami/jenkins] add support for custom Jenkins launcher parameters

### PR DESCRIPTION
**Pull request by haomingz**
### Description of the change

add support for custom Jenkins launcher parameters with JENKINS_OPTS variable

### Benefits

To customize the arguments for the Jenkins launcher in a derived Jenkins image, you can define Jenkins arguments through JENKINS_OPTS. This is particularly useful. 
For instance, if you want to install Jenkins behind a reverse proxy with a prefix such as mysite.com/jenkins, it's necessary to add an environment variable JENKINS_OPTS="--prefix=/jenkins". This option is commonly used for Jenkins.

### CODE REVIEW

**Comment by carrodher** [comment]
Thanks for creating this PR. Please, note it is needed to sign the commits. Your signature certifies that you wrote the patch or otherwise have the right to contribute the material. You can find more info about this topic, in [the “Sign your work” section from the contributing guidelines](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#sign-your-work).

**Comment by haomingz** [comment]
> Thanks for creating this PR. Please, note it is needed to sign the commits. Your signature certifies that you wrote the patch or otherwise have the right to contribute the material. You can find more info about this topic, in [the “Sign your work” section from the contributing guidelines](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#sign-your-work).

Resigned, thank you.

**Review by dgomezleon — CHANGES_REQUESTED** [review]
Thanks for your contribution. I would suggest a couple of changes:
* Add an example under `## Customize this image` section. E.g. the one you explained in the description.
* Add `JENKINS_OPTS` in `2/debian-11/rootfs/opt/bitnami/scripts/jenkins-env.sh`.

**Comment by haomingz** [comment]
> Thanks for your contribution. I would suggest a couple of changes:
> 
> * Add an example under `## Customize this image` section. E.g. the one you explained in the description.
> * Add `JENKINS_OPTS` in `2/debian-11/rootfs/opt/bitnami/scripts/jenkins-env.sh`.

Modifications have been made based on your suggestions.

**Review by dgomezleon — CHANGES_REQUESTED** [review]
Thanks for the changes. Just a minor requirement. Please add `JENKINS_OPTS` inside  `jenkins_env_vars` in `jenkins-env.sh`

**Comment by haomingz** [comment]
> Thanks for the changes. Just a minor requirement. Please add `JENKINS_OPTS` inside `jenkins_env_vars` in `jenkins-env.sh`

Added, thank you for your patient guidance. 😄

**Review by dgomezleon — APPROVED** [review]
Thank you :)

**Pull request merged**
