### PR TITLE
[bitnami/pgbouncer] Add PGBOUNCER_APPLICATION_NAME_ADD_HOST

### PR DESCRIPTION
**Pull request by rbojan**
### Description of the change

Add `PGBOUNCER_APPLICATION_NAME_ADD_HOST` environment variable. See https://github.com/bitnami/containers/issues/68089

### Benefits

PgBouncer setting `application_name_add_host` can be set through an environment variable.

### Possible drawbacks

N/A

### Applicable issues

- #68089

### CODE REVIEW

**Comment by carrodher** [comment]
Thank you for initiating this pull request. We appreciate your effort. Just a friendly reminder that it's important to sign your commits. Adding your signature certifies that you either authored the patch or have the necessary rights to contribute the changes. You can find detailed information on how to do this in the [“Sign your work” section of our contributing guidelines](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#sign-your-work).

Feel free to reach out if you have any questions or need assistance with the signing process.

**Comment by rbojan** [comment]
Thank you for reminding me that it is important to read the Contributing guidelines.

I force pushed my commit with my signature.

**Review by rafariossaa — CHANGES_REQUESTED** [review]
You need to add this new environment variable to `pgbouncer-env.sh`

**Comment by rbojan** [comment]
Added this new environment variable to pgbouncer-env.sh

**Review by rafariossaa — APPROVED** [review]
Thanks for adding this.
LGTM

**Pull request merged**
