### PR TITLE
[bitnami/jasperreports] fix: allow custom email sender address

### PR DESCRIPTION
**Pull request by schakko**
### Description of the change

At some point in the past, the configuration value `SMTP_EMAIL` had been removed. The configuration value is still used in the official Helm chart. Due to the removement, it is no longer possible to configure a custom 'From:' email header if the SMTP username differs from the sender address.

This commit re-introduces `SMTP_EMAIL`. If that pararameter is not available, the SMTP_USER address is used as fallback.

### Benefits

Users with custom e-mail sender verification can send emails.

### Possible drawbacks

Should be none as `SMTP_EMAIL` is optional and a fallback is applied.

### CODE REVIEW

**Comment by carrodher** [comment]
Thanks for creating this PR. Please, note it is needed to sign the commits. Your signature certifies that you wrote the patch or otherwise have the right to contribute the material. You can find more info about this topic, in [the “Sign your work” section from the contributing guidelines](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#sign-your-work).

**Comment by schakko** [comment]
> Thanks for creating this PR. Please, note it is needed to sign the commits. Your signature certifies that you wrote the patch or otherwise have the right to contribute the material. You can find more info about this topic, in [the “Sign your work” section from the contributing guidelines](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#sign-your-work).

Done :-)

**Review by corico44 — DISMISSED** [review]
LGTM! But, @schakko, there are conflict errors with the main branch. Could you fix these errors so I can proceed to merge the changes?

**Comment by schakko** [comment]
@corico44 Sorry for the late response, somehow the GH notification did not appear in my inbox.
I've fixed the conflict, so we should be good to go.

**Comment by corico44** [comment]
Hello @schakko,
It seems that the modification you initially proposed is already applied in the container, so no change appears in this PR.

**Pull request closed without merging**
