### PR TITLE
[bitnami/pgbouncer] Add max_prepared_statements to available environment variables

### PR DESCRIPTION
**Pull request by bayandin**
### Description of the change

Add `PGBOUNCER_MAX_PREPARED_STATEMENTS` env variable which translates into `max_prepared_statements` PgBouncer config parameter.

### Benefits

It allows to enable support for prepared statements in PgBouncer

### Possible drawbacks

None, it's disabled by default

### Applicable issues

None

### Additional information

PgBouncer 1.21.0 has introduced support for prepared statements, to enable it, it requires setting `max_prepared_statements` parameter, see https://www.pgbouncer.org/config.html#max_prepared_statements

### CODE REVIEW

**Review by juan131 — APPROVED** [review]
Thanks so much for your contributions! Your changes LGTM

**Comment by eidam** [comment]
👋 thank you for the contribution! how can I use the `PGBOUNCER_MAX_PREPARED_STATEMENTS` with the `1.21.0` dockerhub image? does it need to be rebuilt?

**Comment by bayandin** [comment]
> does it need to be rebuilt?

Yes, the image should be rebuilt by bitnami folks. 
The latest version (`1.21.0-debian-11-r1`) doesn't contain these changes yet.


Alternatively, if you don't want to wait, you can experiment with it by replacing the following files in the current image 
- `/opt/bitnami/scripts/libpgbouncer.sh` with [`bitnami/pgbouncer/1/debian-11/rootfs/opt/bitnami/scripts/libpgbouncer.sh` ](https://github.com/bitnami/containers/blob/main/bitnami/pgbouncer/1/debian-11/rootfs/opt/bitnami/scripts/libpgbouncer.sh)
- `/opt/bitnami/scripts/pgbouncer-env.sh` with [`bitnami/pgbouncer/1/debian-11/rootfs/opt/bitnami/scripts/pgbouncer-env.sh`](https://github.com/bitnami/containers/blob/main/bitnami/pgbouncer/1/debian-11/rootfs/opt/bitnami/scripts/pgbouncer-env.sh)

Something like this (I didn't test it):
```dockerfile
FROM bitnami/pgbouncer:1.21.0-debian-11-r1

COPY libpgbouncer.sh  /opt/bitnami/scripts/libpgbouncer.sh
COPY pgbouncer-env.sh /opt/bitnami/scripts/pgbouncer-env.sh
```

**Comment by juan131** [comment]
Hi everyone,

Could you please give it a try to the latest `1.21.0-debian-11-r3` version we just released? Thanks in advance.

**Pull request merged**
